### ISSUE TITLE
unused token numbering oddities

### ISSUE THREAD

**Issue by balmas** [latin-language-toolkit/arethusa#597]
Reported by Vanessa (commit fda49297242e6423863e6391e9df62fb5d6b86cd ):

The numbering has some oddities.  I am talking about where it tells you how many words are unused either on the left side (how many you have not hung on the tree) or in the right side under the relation tab, where it tells you how many have not been assigned a relation.   I refreshed the file and opened the next untreed sentence.  Two of my three defaults are preset (that is, the keyboard is disabled and the relations are set to Advanced Mode).  Morph does not have the Expanded Selection prechecked, and, when I do it manually, nothing is preselected.  The number on the left says “0 unused’, even though nothing has been done yet and the “highlight unused” button does nothing. I have no clue what the “Selection” and “none” buttons are supposed to do, since I cannot see that they do anything just now.   The number on the right on the relation tab says “30 of 35” which I suspect is correct.  However, if I move forward to other sentences without doing this tree, every one of them says xx of 35 unused, no matter how many words are in it (“75 of 35 unused”).

 As I start to build the tree, the number of unused tokens decreases on the left from 0 into negative numbers.  Since I cannot tell how many words are in the sentence, I do not know when all are hung.  “Highlight unused” still does not work.  When I added in two elided words, the number on the right correctly changed to read 32 out of 37.  Now all subsequent sentences also say “xx out of 37.”

When I am done hanging the tree, but have done no labeling, the number on the left says -32 unused and the one on the right says 32 of 37 unused.

**Comment by balmas** [comment]
Comments from Vanessa:
The numbers on the left appear to be working correctly.  Good fix!  There is still an oddity in the numbers in the Relation box.  If you go to a sentence that is not yet treed, and let's say it says 11 of 13 unused.  If you skip to the next sentence without doing anything to that first sentence, it will say 35 of 13 unused.  I haven't sorted out the exact circumstances, but it keeps the total number from the first sentence that has not been done.   

Another thing I would note about the numbers on the left: if you add in elided forms, then the total will be in negative numbers.  So when I added in two elided forms andmy whole tree was hung, it said -2 unused.  That works fine, so long as one knows that it works that way and doesn't stop hanging items at "0 unused."

I think it is keeping the total number of words from whatever sentence you first open up.

**Comment by LFDM** [comment]
Wrong total numbers fixed in b3f0d2c23de29d637555af59e19b95236fcf78bb

**Comment by LFDM** [comment]
Fixed problems with elided forms in 630177be9aa425f7c68119795151344c88b1bc08

@Christof, can you confirm I did this right? If yes (I think I did), close this issue.

Do we want to display the total number of tokens in the tokenSelector? I'd vote yes.

**Comment by Christof** [comment]
Confirm total numbers fix: see 156882a76c102ce14345aa754bb5cf1903fea13a (you contribution thief :smirk:)
I've also partially fixed the elided forms, although the formatting did not propagate. Your change also looks good, but now we can remove the `tokenAdded` and `tokenRemoved` events from the unused highlighter.
Where would you display the total number?

**Comment by balmas** [comment]
I think we can close this now?
